### ISSUE TITLE
Enchanted books are disappeared in creative mode inventory

### ISSUE THREAD

**Issue by GoldenTotem** [Fuzss/universalenchants-forge#1]
Many enchanted books such as sharpness and power are disappeared in creative mode inventory, only a part of them remains.

1.16.5  forge_36.2.23  Sneaky Magic_1.3.2

**Comment by Fuzss** [comment]
Fixed in 1.18 release. 1.16 release of Sneaky Magic will not receive the fix due to time constraints unfortunately though.
