### ISSUE TITLE
Crossbow with infinity doesn't work normally

### ISSUE THREAD

**Issue by GoldenTotem** [Fuzss/universalenchants-forge#2]
Bow with infinity only works with normal arrows, but crossbow with infinity works with all kinds of arrows such as spectral arrows and tipped arrows.

1.16.5  forge_36.2.23  Sneaky Magic_1.3.2

**Comment by Fuzss** [comment]
Fixed in 1.18 release. 1.16 release of Sneaky Magic will not receive the fix due to time constraints unfortunately though.
