### ISSUE TITLE
[Compatibility] Enchantments from Ensorcellation don't obey exclusivity config

### ISSUE THREAD

**Issue by chimericdream** [Fuzss/universalenchants-forge#3]
I tested this in a copy of my modpack, and everything seems to be working (mostly) great! However, I noticed that enchantments from the Ensorcellation mod cannot be applied to weapons and armor when the item contains enchants that would normally be mutually exclusive. Is that something on your side, or should I report the issue to them?

Thanks!

**Comment by Fuzss** [comment]
The mod has been rewritten (and renamed) for 1.18, if this is a problem please reopen the issue. 1.16 release of Sneaky Magic is no longer supported due to time constraints unfortunately though.
