### ISSUE TITLE
Thrown trident with knockback doesn't work normally

### ISSUE THREAD

**Issue by GoldenTotem** [Fuzss/universalenchants-forge#4]
Knockback enchantment on a trident works normally when you hold it in your hand. But if you throw it, the trident will pull mobs toward yourself instead of push them away. In other words, the direction of knockback is reversed.

1.16.5  forge_36.2.23  Sneaky Magic_1.3.2

**Comment by Fuzss** [comment]
Fixed in 1.18 release. 1.16 release of Sneaky Magic will not receive the fix due to time constraints unfortunately though.

**Comment by GoldenTotem** [comment]
> Fixed in 1.18 release. 1.16 release of Sneaky Magic will not receive the fix due to time constraints unfortunately though.

That's too regretful, I just want to use it in my 1.16.5 modpack. If there is no time constraints, please consider it, thank you :)
