### ISSUE TITLE
[Crash] Exception Ticking World.

### ISSUE THREAD

**Issue by Corvus20** [Fuzss/universalenchants-forge#6]
I don't know exactly WHY it is causing a crash, though. Perhaps you can help?

[crash-2022-03-25_17.16.03-server.txt](https://github.com/Fuzss/universalenchants-forge/files/8353846/crash-2022-03-25_17.16.03-server.txt)

**Comment by Fuzss** [comment]
Should be fixed in v3.0.4. Please reopen this issue if the crash reoccurs.
